name: Build and Deploy
on:
  push:
    branches: [dev]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          # TARGET_REPO: username/repo
          TARGET_BRANCH: master
          BUILD_SCRIPT: npm i 
          BUILD_SCRIPT: npm run build
          BUILD_DIR: docs
